#name: Deploy Build to PyPi
#
#on:
#  push:
#    branches:
#      - main
#  workflow_dispatch:
#
#  jobs:
#    build-and-deploy:
#      runs-on: ubuntu-latest
#
#      env:
#        PYPI_KEY: ${{secrents.PYPI_KEY}}
#    
#  steps:
